# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-03-18 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_auto_20200915_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[(b'C', b'Conference'), (b'E', b'Event'), (b'EX', b'Exhibition'), (b'L', b'Lecture'), (b'M', b'Meeting'), (b'PE', b'Press Event'), (b'T', b'Talk'), (b'W', b'Workshop'), (b'ED', b'Educational event'), (b'TT', b'Teacher Training'), (b'CS', b'Citizen Science'), (b'LC', b'Local Community Event')], db_index=True, default=b'T', help_text=b'The event and meeting type is used to control where the event is displayed on the website.', max_length=2),
        ),
    ]
