# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-24 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20210318_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='audience',
            field=models.CharField(choices=[(b'I', b'Internal'), (b'P', b'Public'), (b'S', b'Science')], db_index=True, default=b'P', help_text=b'The event and meeting audience is used to control which audience is targetted.', max_length=2),
        ),
        migrations.AlterField(
            model_name='event',
            name='type',
            field=models.CharField(choices=[(b'C', b'Conference'), (b'E', b'Event'), (b'EX', b'Exhibition'), (b'PE', b'Press Event'), (b'T', b'Talk'), (b'ED', b'Educational event'), (b'TT', b'Teacher Training'), (b'CS', b'Citizen Science'), (b'LC', b'Local Community Event')], db_index=True, default=b'T', help_text=b'The event and meeting type is used to control where the event is displayed on the website.', max_length=2),
        ),
    ]
