# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-06-24 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_auto_20210624_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[(b'H', b'Html'), (b'I', b'ICAL'), (b'X', b'XML')], max_length=1)),
                ('url', models.URLField(max_length=255, verbose_name=b'Calendar URL')),
            ],
        ),
    ]
